pipeline {
    agent any
    parameters {
        choice(choices: ['TEST','DEV','PROD'], description: 'Which env', name: 'deployEnv')
    }
    stages {
        stage('Demo'){
            steps {
                echo "Env is set to ${params.deployEnv}"
            }
        }
    }
}