pipeline {
    agent any
    parameters {
        string(defaultValue: 'Test', description: 'Which env', name: 'deployEnv')
    }
    stages {
        stage('Demo'){
            steps {
                echo "Env is set to ${params.deployEnv}"
            }
        }
    }
}